# Generated by Django 6.1 on 2026-08-25 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_initial_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('model_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=10, null=True)),
                ('chassis', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PURCHASED', 'Comprado'), ('IN_PREPARATION', 'Em preparação'), ('READY', 'Pronto'), ('LISTED', 'Anunciado'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], default='PURCHASED', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fipe_reference_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fipe_code', models.CharField(blank=True, max_length=20, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.company')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
    ]
