# Generated by Django 6.1 on 2026-08-25 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import vehicles.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_create_internal_code_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleExpense',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('ACQUISITION', 'Aquisição'), ('YARD_RELEASE', 'Pátio/Liberação'), ('TRANSPORT', 'Transporte'), ('DOCUMENTATION', 'Documentação'), ('MECHANICAL', 'Mecânica'), ('BODYWORK', 'Funilaria'), ('PAINTING', 'Pintura'), ('DETAILING', 'Estética'), ('CLEANING', 'Higienização'), ('PARTS', 'Peças'), ('ACCESSORIES', 'Acessórios'), ('MARKETING', 'Marketing'), ('COMMISSION', 'Comissão'), ('OTHER', 'Outros')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Despesa do veículo',
                'verbose_name_plural': 'Despesas do veículo',
            },
        ),
        migrations.CreateModel(
            name='VehicleValueChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(choices=[('asking_price', 'Preço anunciado'), ('sale_price', 'Preço de venda')], max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='value_change_logs', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Log de alteração de valor',
                'verbose_name_plural': 'Logs de alteração de valor',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=vehicles.models.vehicle_photo_upload_path)),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=vehicles.models.vehicle_photo_thumbnail_upload_path)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Foto do veículo',
                'verbose_name_plural': 'Fotos do veículo',
                'ordering': ['position', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('vehicle',), name='unique_cover_photo_per_vehicle')],
            },
        ),
    ]
