# Generated by Django 6.1 on 2026-08-26 18:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleexpense_vehiclevaluechangelog_vehiclephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
